# Q-Q 哈密顿量模拟

含有两个Qubit的结构，验证其耦合强度如何影响本征频率

In [1]:
from qutip import destroy, qeye, tensor
import matplotlib.pyplot as plt
import numpy as np

## EPR结果

In [2]:
# Eigenmode(MHz)
freq_q1 = 5000
freq_q2 = 5000

In [3]:
# Coupling Strength
g = 10

## 构建哈密顿量

In [4]:
# 单体希尔伯特空间维度
N = 2

In [5]:
# 构建湮灭、创生算符
a = destroy(N)
a_dag = a.dag()
# 单位算符
I = qeye(N)

In [6]:
# 构建多体系统算符
a_q1 = tensor([a, I, I])
a_q1_dag = a_q1.dag()

a_q2 = tensor([I, a, I])
a_q2_dag = a_q2.dag()

In [7]:
# 哈密顿量线性部分
Ham = freq_q1 * a_q1_dag * a_q1 + freq_q2 * a_q2_dag * a_q2 + g * (a_q1_dag * a_q2 + a_q1 * a_q2_dag)
Ham

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[    0.     0.     0.     0.     0.     0.     0.     0.]
 [    0.     0.     0.     0.     0.     0.     0.     0.]
 [    0.     0.  5000.     0.    10.     0.     0.     0.]
 [    0.     0.     0.  5000.     0.    10.     0.     0.]
 [    0.     0.    10.     0.  5000.     0.     0.     0.]
 [    0.     0.     0.    10.     0.  5000.     0.     0.]
 [    0.     0.     0.     0.     0.     0. 10000.     0.]
 [    0.     0.     0.     0.     0.     0.     0. 10000.]]

In [9]:
# 哈密顿量非线性部分
Ham.eigenenergies()

array([    0.,     0.,  4990.,  4990.,  5010.,  5010., 10000., 10000.])

In [10]:
# Normal mode 方法
freq_q1_nm = 4990
freq_q2_nm = 5010
g = np.sqrt(((freq_q1_nm ** 2 - freq_q2_nm ** 2)**2 - (freq_q1 **2 - freq_q2 **2)**2) / (16 * freq_q1 * freq_q2))
g

10.0

**结果**

- Normal Mode方法与哈密顿量对角化方法得到的结果一致

$$g = \sqrt{\frac{(\tilde \omega_0^2 - \tilde \omega_1^2)^2 - (\omega_0^2 - \omega_1^2)^2}{16\omega_0 \omega_1}}$$